#!/usr/bin/env ruby

require 'securerandom'
require 'time'

SERVICES = [
  :alpha,
  :bravo,
  :charlie,
  :delta,
  :echo,
  :foxtrot,
  :gamma,
  :hawaii,
  :indigo,
  :julia,
  :kilo,
  :lemur,
  :milan,
  :noise,
  :oscar
]

class Span
  attr_reader :service
  attr_reader :sub_spans
  attr_reader :start_time

  INTERNAL_DURATION_RANGE = (50..300)
  
  def initialize(service)
    @service = service
    @sub_spans = []
  end

  def span_id
    @_span_id ||= SecureRandom.uuid
  end

  def duration
    if sub_spans.empty?
      internal_duration
    else
      sub_span_durations = sub_spans.map(&:duration).reduce(:+)
      sub_span_durations + internal_duration
    end
  end

  def end_time
    start_time + (duration.to_f/1000)
  end

  def external_duration
    return 0 if sub_spans.empty?

    child_durations = sub_spans.map(&:duration)
    if child_spans_are_parallel
      child_durations.max
    else
      child_durations.reduce(:+)
    end
  end

  def child_spans_are_parallel
    @_child_spans_are_parallel ||= (rand(2) == 0)
  end

  def add_sub_span(sub_span)
    sub_spans << sub_span
  end

  def build_start_times(start_time)
    @start_time = start_time

    #puts service.to_s + ": " + sub_spans.map(&:service).join(", ")
    sub_spans.inject(start_time) do |sub_span_start_time,sub_span|

      sub_span.build_start_times(sub_span_start_time)
      #puts "#{sub_span.service} #{sub_span.start_time.to_i} -> #{sub_span.end_time.to_i}"

      if child_spans_are_parallel
        sub_span_start_time
      else
        sub_span.end_time
      end
    end
  end

  def generate_fake_log_lines(trace_id=SecureRandom.uuid, parent_span_id = '')
    log_fields = {
      Correlation_ID: trace_id,
      spanId: span_id,
      parentSpanId: parent_span_id,
      elapsedMillis: duration,
      service: service
    }

    log_line = log_fields
      .map{ |k,v| "#{k}=#{v}" }
      .unshift(end_time.iso8601(5))
      .join(" ")


    sub_span_log_lines = sub_spans.map do |sub_span| 
      sub_span.generate_fake_log_lines(trace_id,span_id)
    end

    sub_span_log_lines + [log_line]
  end

  def inspect(depth=0)
    sub_span_desc = sub_spans.map do |sub_span|
      sub_span.inspect(depth+1)
    end
    
    lines = [
      "#{service}: #{duration}",
      sub_span_desc
    ].flatten

    indent = "  "*depth
    lines.map{ |line| indent + line }.join("\n")
  end

  private
  
  def internal_duration
    @_internal_duration ||= (INTERNAL_DURATION_RANGE.begin+rand(INTERNAL_DURATION_RANGE.end))
  end
end

def remove_random_elements_from_array!(array,n)
  elements = array.sample(n)
  array.delete_if{ |x| elements.include?(x) }
  elements
end

def generate_sub_topology(available_services)
  return {} if available_services.empty?

  # choose a random number of child spans between 1 and 3
  num_child_services = 0+rand(3)
  child_services = remove_random_elements_from_array!(available_services,num_child_services)

  child_topology = {}
  child_services.each do |child_service|
    sub_topology = generate_sub_topology(available_services)
    child_topology[child_service] = sub_topology
  end

  child_topology
end  

def generate_topology
  available_services = SERVICES.dup
  {
    root_service: generate_sub_topology(available_services)
  }
end


def generate_trace_for_topology(topology)
  raise 'badly structured topology' unless topology.size == 1

  service = topology.keys.first
  sub_services = topology.values.first
  map_subtopology_to_subspan(service,sub_services)
end

def map_subtopology_to_subspan(service,sub_services)
  span = Span.new(service)
  sub_services.each do |sub_service,sub_sub_services|
    sub_span = map_subtopology_to_subspan(sub_service,sub_sub_services)
    span.add_sub_span(sub_span)
  end
  span
end

num_traces = ARGV.empty? ? 1 : (ARGV.first.to_i)


num_traces.times do 
  topology = generate_topology
  #require 'yaml'
  #puts topology.to_yaml
  trace = generate_trace_for_topology(topology)
  trace.build_start_times(Time.now)
  puts trace.generate_fake_log_lines.join("\n")
end
